import type {
  AuthResponse,
  Classroom,
  ChildListItem,
  ChildDetail,
  DashboardSummary,
  SafetyCheckListItem,
  SafetyCheckDetail,
} from './types'

export const MOCK_AUTH: AuthResponse = {
  access_token: 'mock-offline-token',
  token_type: 'bearer',
  login_method: 'DEMO',
  user: {
    id: 1,
    email: 'teacher@ddakkok.com',
    name: '김하늘',
    role: 'TEACHER',
    facility: { id: 1, name: '땅콩어린이집', facility_type: 'DAYCARE' },
    classroom: { id: 1, name: '햇님반', age_group: '만 3세' },
  },
}

export const MOCK_CLASSROOMS: Classroom[] = [
  { id: 1, facility_id: 1, name: '햇님반', age_group: '만 3세' },
  { id: 2, facility_id: 1, name: '별님반', age_group: '만 4세' },
]

const CLASSROOM_1_CHILDREN: ChildListItem[] = [
  { id: 1, facility_id: 1, classroom_id: 1, name: '강민준', birth_date: '2022-03-15', gender: 'M', memo: '우유 알레르기 주의', is_active: true },
  { id: 2, facility_id: 1, classroom_id: 1, name: '김서아', birth_date: '2022-07-20', gender: 'F', memo: '민감성 피부', is_active: true },
  { id: 3, facility_id: 1, classroom_id: 1, name: '박도윤', birth_date: '2022-01-08', gender: 'M', memo: null, is_active: true },
  { id: 4, facility_id: 1, classroom_id: 1, name: '이지은', birth_date: '2022-11-30', gender: 'F', memo: '땅콩 알레르기', is_active: true },
  { id: 5, facility_id: 1, classroom_id: 1, name: '오시우', birth_date: '2021-06-12', gender: 'M', memo: null, is_active: true },
]

const CLASSROOM_2_CHILDREN: ChildListItem[] = [
  { id: 6, facility_id: 1, classroom_id: 2, name: '최유진', birth_date: '2021-04-05', gender: 'F', memo: null, is_active: true },
  { id: 7, facility_id: 1, classroom_id: 2, name: '정우혁', birth_date: '2021-09-14', gender: 'M', memo: '아토피 피부', is_active: true },
]

export const MOCK_CHILDREN_BY_CLASSROOM: Record<number, ChildListItem[]> = {
  1: CLASSROOM_1_CHILDREN,
  2: CLASSROOM_2_CHILDREN,
}

export const MOCK_CHILD_DETAILS: Record<number, ChildDetail> = {
  1: {
    id: 1, facility_id: 1, classroom_id: 1, name: '강민준',
    birth_date: '2022-03-15', gender: 'M', memo: '우유 알레르기 주의', is_active: true,
    health_profile: {
      allergies: ['우유'],
      skin_conditions: [],
      sensitive_ingredients: ['카제인나트륨', '카제인Na'],
      notes: '우유 및 우유 유래 성분 섭취·접촉 주의',
    },
  },
  2: {
    id: 2, facility_id: 1, classroom_id: 1, name: '김서아',
    birth_date: '2022-07-20', gender: 'F', memo: '민감성 피부', is_active: true,
    health_profile: {
      allergies: [],
      skin_conditions: ['민감성 피부'],
      sensitive_ingredients: ['향료', '페녹시에탄올'],
      notes: '향료 함유 제품 사용 시 패치 테스트 권장',
    },
  },
  3: {
    id: 3, facility_id: 1, classroom_id: 1, name: '박도윤',
    birth_date: '2022-01-08', gender: 'M', memo: null, is_active: true,
    health_profile: { allergies: [], skin_conditions: [], sensitive_ingredients: [], notes: null },
  },
  4: {
    id: 4, facility_id: 1, classroom_id: 1, name: '이지은',
    birth_date: '2022-11-30', gender: 'F', memo: '땅콩 알레르기', is_active: true,
    health_profile: {
      allergies: ['땅콩'],
      skin_conditions: [],
      sensitive_ingredients: [],
      notes: '땅콩 유래 성분 함유 제품 사용 금지',
    },
  },
  5: {
    id: 5, facility_id: 1, classroom_id: 1, name: '오시우',
    birth_date: '2021-06-12', gender: 'M', memo: null, is_active: true,
    health_profile: { allergies: [], skin_conditions: [], sensitive_ingredients: [], notes: null },
  },
  6: {
    id: 6, facility_id: 1, classroom_id: 2, name: '최유진',
    birth_date: '2021-04-05', gender: 'F', memo: null, is_active: true,
    health_profile: { allergies: [], skin_conditions: [], sensitive_ingredients: [], notes: null },
  },
  7: {
    id: 7, facility_id: 1, classroom_id: 2, name: '정우혁',
    birth_date: '2021-09-14', gender: 'M', memo: '아토피 피부', is_active: true,
    health_profile: {
      allergies: [],
      skin_conditions: ['아토피 피부염'],
      sensitive_ingredients: ['향료', '에탄올'],
      notes: '건조한 날씨에 특히 주의 필요',
    },
  },
}

export const MOCK_SAFETY_CHECKS: SafetyCheckListItem[] = [
  {
    id: 35,
    product: { id: 102, name: '밀크 프로틴 보습 물티슈', category: 'WET_TISSUE' },
    classroom_id: 1,
    overall_status: 'FAIL',
    pass_count: 3,
    warn_count: 1,
    fail_count: 1,
    expired_count: 0,
    unknown_count: 0,
    total_count: 5,
    children: [
      { child_id: 1, child_name: '강민준', status: 'FAIL', status_label: '사용 보류' },
      { child_id: 2, child_name: '김서아', status: 'WARN', status_label: '주의 필요' },
      { child_id: 3, child_name: '박도윤', status: 'PASS', status_label: '사용 가능' },
      { child_id: 4, child_name: '이지은', status: 'PASS', status_label: '사용 가능' },
      { child_id: 5, child_name: '오시우', status: 'PASS', status_label: '사용 가능' },
    ],
    created_at: '2026-06-10T09:30:00',
  },
  {
    id: 34,
    product: { id: 103, name: '향기 톡톡 키즈 로션', category: 'LOTION' },
    classroom_id: 1,
    overall_status: 'WARN',
    pass_count: 4,
    warn_count: 1,
    fail_count: 0,
    expired_count: 0,
    unknown_count: 0,
    total_count: 5,
    children: [
      { child_id: 1, child_name: '강민준', status: 'PASS', status_label: '사용 가능' },
      { child_id: 2, child_name: '김서아', status: 'WARN', status_label: '주의 필요' },
      { child_id: 3, child_name: '박도윤', status: 'PASS', status_label: '사용 가능' },
      { child_id: 4, child_name: '이지은', status: 'PASS', status_label: '사용 가능' },
      { child_id: 5, child_name: '오시우', status: 'PASS', status_label: '사용 가능' },
    ],
    created_at: '2026-06-09T14:15:00',
  },
  {
    id: 33,
    product: { id: 104, name: '세이프 데일리 핸드워시', category: 'CLEANSER' },
    classroom_id: 1,
    overall_status: 'PASS',
    pass_count: 5,
    warn_count: 0,
    fail_count: 0,
    expired_count: 0,
    unknown_count: 0,
    total_count: 5,
    children: [
      { child_id: 1, child_name: '강민준', status: 'PASS', status_label: '사용 가능' },
      { child_id: 2, child_name: '김서아', status: 'PASS', status_label: '사용 가능' },
      { child_id: 3, child_name: '박도윤', status: 'PASS', status_label: '사용 가능' },
      { child_id: 4, child_name: '이지은', status: 'PASS', status_label: '사용 가능' },
      { child_id: 5, child_name: '오시우', status: 'PASS', status_label: '사용 가능' },
    ],
    created_at: '2026-06-08T11:00:00',
  },
  {
    id: 32,
    product: { id: 108, name: '유통기한 지난 물티슈', category: 'WET_TISSUE' },
    classroom_id: 1,
    overall_status: 'EXPIRED',
    pass_count: 0,
    warn_count: 0,
    fail_count: 0,
    expired_count: 5,
    unknown_count: 0,
    total_count: 5,
    children: [
      { child_id: 1, child_name: '강민준', status: 'EXPIRED', status_label: '기한 만료' },
      { child_id: 2, child_name: '김서아', status: 'EXPIRED', status_label: '기한 만료' },
      { child_id: 3, child_name: '박도윤', status: 'EXPIRED', status_label: '기한 만료' },
      { child_id: 4, child_name: '이지은', status: 'EXPIRED', status_label: '기한 만료' },
      { child_id: 5, child_name: '오시우', status: 'EXPIRED', status_label: '기한 만료' },
    ],
    created_at: '2026-06-07T16:45:00',
  },
]

export const MOCK_CHECK_DETAILS: Record<number, SafetyCheckDetail> = {
  35: {
    id: 35,
    product: {
      id: 102, name: '밀크 프로틴 보습 물티슈', category: 'WET_TISSUE',
      manufacturer: '해커톤생활건강', barcode: '880100000102',
      expiry_date: '2027-08-31',
      ingredients: ['정제수', '글리세린', '카제인나트륨', '페녹시에탄올', '향료'],
      normalized_ingredients: ['정제수', '글리세린', '카제인나트륨', '페녹시에탄올', '향료'],
    },
    classroom_id: 1,
    summary: { overall_status: 'FAIL', pass_count: 3, warn_count: 1, fail_count: 1, expired_count: 0, unknown_count: 0, total_count: 5 },
    results: [
      {
        child_id: 1, child_name: '강민준', status: 'FAIL', status_label: '사용 보류',
        matched_ingredients: ['카제인나트륨'],
        matched_rule_code: 'ALLERGY_DIRECT',
        matched_profile: '우유',
        matched_ingredient: '카제인나트륨',
        reason: '알레르기 유발 성분(카제인나트륨) 함유',
        teacher_sentence: '강민준 어린이는 우유 알레르기가 있어 카제인나트륨이 포함된 이 제품을 사용하면 알레르기 반응이 일어날 수 있어요.',
        explanation: '카제인나트륨은 우유 단백질인 카제인에서 유래한 성분으로, 우유 알레르기 아동에게 접촉 또는 섭취 시 두드러기, 가려움증 등의 반응을 유발할 수 있습니다. 즉시 사용을 중단하고 대체 제품을 선택하세요.',
      },
      {
        child_id: 2, child_name: '김서아', status: 'WARN', status_label: '주의 필요',
        matched_ingredients: ['향료', '페녹시에탄올'],
        matched_rule_code: 'SENSITIVE_INGREDIENT',
        matched_profile: '민감성 피부',
        matched_ingredient: '향료',
        reason: '민감 성분(향료, 페녹시에탄올) 함유',
        teacher_sentence: '김서아 어린이는 민감성 피부로 향료와 페녹시에탄올에 주의가 필요해요. 소량 테스트 후 이상 반응이 없으면 주의하며 사용하세요.',
        explanation: '향료는 민감성 피부를 가진 아이에게 자극과 홍반을 유발할 수 있는 성분입니다. 페녹시에탄올은 방부제로 일부 민감한 피부에 자극을 줄 수 있습니다. 처음 사용 시 손목 안쪽에 소량 도포 후 10분 관찰하세요.',
      },
      {
        child_id: 3, child_name: '박도윤', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [],
        matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '박도윤 어린이는 이 제품의 모든 성분에 이상이 없어 안전하게 사용할 수 있어요.',
        explanation: null,
      },
      {
        child_id: 4, child_name: '이지은', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [],
        matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '이지은 어린이는 이 제품의 모든 성분에 이상이 없어 안전하게 사용할 수 있어요.',
        explanation: null,
      },
      {
        child_id: 5, child_name: '오시우', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [],
        matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '오시우 어린이는 이 제품의 모든 성분에 이상이 없어 안전하게 사용할 수 있어요.',
        explanation: null,
      },
    ],
    overall_explanation: '이 제품에는 우유 단백질 유래 성분인 카제인나트륨이 함유되어 있어 우유 알레르기가 있는 강민준 어린이에게 사용을 중단하도록 조치하세요. 민감성 피부인 김서아 어린이도 향료와 페녹시에탄올로 인해 주의가 필요합니다. 나머지 3명은 안전하게 사용 가능합니다.',
  },
  34: {
    id: 34,
    product: {
      id: 103, name: '향기 톡톡 키즈 로션', category: 'LOTION',
      manufacturer: '키즈뷰티랩', barcode: '880100000103',
      expiry_date: '2027-12-31',
      ingredients: ['정제수', '글리세린', '스쿠알란', '향료', '토코페롤'],
      normalized_ingredients: ['정제수', '글리세린', '스쿠알란', '향료', '토코페롤'],
    },
    classroom_id: 1,
    summary: { overall_status: 'WARN', pass_count: 4, warn_count: 1, fail_count: 0, expired_count: 0, unknown_count: 0, total_count: 5 },
    results: [
      {
        child_id: 1, child_name: '강민준', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '강민준 어린이는 이 제품을 안전하게 사용할 수 있어요.',
        explanation: null,
      },
      {
        child_id: 2, child_name: '김서아', status: 'WARN', status_label: '주의 필요',
        matched_ingredients: ['향료'],
        matched_rule_code: 'SENSITIVE_INGREDIENT',
        matched_profile: '민감성 피부',
        matched_ingredient: '향료',
        reason: '민감 성분(향료) 함유',
        teacher_sentence: '김서아 어린이는 민감성 피부로 향료 성분에 주의가 필요해요. 소량 테스트 후 이상이 없으면 주의하며 사용하세요.',
        explanation: null,
      },
      {
        child_id: 3, child_name: '박도윤', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '박도윤 어린이는 이 제품을 안전하게 사용할 수 있어요.',
        explanation: null,
      },
      {
        child_id: 4, child_name: '이지은', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '이지은 어린이는 이 제품을 안전하게 사용할 수 있어요.',
        explanation: null,
      },
      {
        child_id: 5, child_name: '오시우', status: 'PASS', status_label: '사용 가능',
        matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
        reason: '해당 없음',
        teacher_sentence: '오시우 어린이는 이 제품을 안전하게 사용할 수 있어요.',
        explanation: null,
      },
    ],
    overall_explanation: '이 로션은 대부분의 아이에게 안전하나, 민감성 피부인 김서아 어린이에게 향료 성분이 자극이 될 수 있습니다. 처음 사용 시 소량 테스트 후 진행하세요.',
  },
  33: {
    id: 33,
    product: {
      id: 104, name: '세이프 데일리 핸드워시', category: 'CLEANSER',
      manufacturer: '해커톤생활건강', barcode: '880100000101',
      expiry_date: '2027-12-31',
      ingredients: ['정제수', '글리세린', '코코베타인', '구연산'],
      normalized_ingredients: ['정제수', '글리세린', '코코베타인', '구연산'],
    },
    classroom_id: 1,
    summary: { overall_status: 'PASS', pass_count: 5, warn_count: 0, fail_count: 0, expired_count: 0, unknown_count: 0, total_count: 5 },
    results: [1, 2, 3, 4, 5].map(id => ({
      child_id: id,
      child_name: ['강민준', '김서아', '박도윤', '이지은', '오시우'][id - 1],
      status: 'PASS' as const, status_label: '사용 가능',
      matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
      reason: '해당 없음',
      teacher_sentence: `${['강민준', '김서아', '박도윤', '이지은', '오시우'][id - 1]} 어린이는 이 제품을 안전하게 사용할 수 있어요.`,
      explanation: null,
    })),
    overall_explanation: '모든 아이에게 안전한 제품입니다. 자연 유래 성분으로 구성되어 영유아에게 적합합니다.',
  },
  32: {
    id: 32,
    product: {
      id: 108, name: '유통기한 지난 물티슈', category: 'WET_TISSUE',
      manufacturer: '해커톤생활건강', barcode: '880100000108',
      expiry_date: '2025-06-01',
      ingredients: ['정제수', '글리세린', '페녹시에탄올'],
      normalized_ingredients: ['정제수', '글리세린', '페녹시에탄올'],
    },
    classroom_id: 1,
    summary: { overall_status: 'EXPIRED', pass_count: 0, warn_count: 0, fail_count: 0, expired_count: 5, unknown_count: 0, total_count: 5 },
    results: [1, 2, 3, 4, 5].map(id => ({
      child_id: id,
      child_name: ['강민준', '김서아', '박도윤', '이지은', '오시우'][id - 1],
      status: 'EXPIRED' as const, status_label: '기한 만료',
      matched_ingredients: [], matched_rule_code: null, matched_profile: null, matched_ingredient: null,
      reason: '유통기한 만료 (2025-06-01)',
      teacher_sentence: `이 제품은 유통기한이 2025년 6월 1일에 만료되었습니다. 사용하지 마세요.`,
      explanation: null,
    })),
    overall_explanation: '유통기한이 만료된 제품입니다. 즉시 폐기하고 새 제품으로 교체하세요.',
  },
}

export const MOCK_DASHBOARD: DashboardSummary = {
  recall_alerts: [
    {
      id: 1,
      product_name: '마이디데이 브로멜라인',
      manufacturer: '주식회사 피비에이치',
      category: '식품',
      recall_date: '2026-04-23',
      reason: '표시대상 알레르기 유발 원료성분(우유, 대두) 미표시',
      action_guide: '해당 제품은 섭취를 중단하고 구입처 또는 판매처에 반품하세요.',
      is_new: true,
      severity: 'HIGH',
    },
    {
      id: 4,
      product_name: '올포홈 구르미 낮잠패드(쿠앤크)',
      manufacturer: '㈜올포홈리빙',
      category: '유아용 섬유제품',
      recall_date: '2026-05-21',
      reason: '폼알데하이드 기준치 초과',
      action_guide: '해당 제품은 사용을 중단하고 판매처 또는 사업자 안내에 따라 교환·환불 절차를 확인하세요.',
      is_new: true,
      severity: 'HIGH',
    },
    {
      id: 5,
      product_name: '키즈 내추럴 선크림 SPF50',
      manufacturer: '자연담은화장품',
      category: '화장품',
      recall_date: '2026-06-01',
      reason: '납 기준치(20μg/g) 초과 검출',
      action_guide: '즉시 사용을 중단하고 구입처에서 환불받으세요.',
      is_new: false,
      severity: 'HIGH',
    },
  ],
  expiry_alerts: [
    {
      product_id: 108,
      product_name: '유통기한 지난 물티슈',
      expiry_date: '2025-06-01',
      alert_type: 'EXPIRED',
      message: '유통기한이 만료된 제품입니다.',
      severity: 'HIGH',
    },
    {
      product_id: 109,
      product_name: '임박한 베이비 로션',
      expiry_date: '2026-06-30',
      alert_type: 'EXPIRING',
      message: '30일 이내 유통기한이 만료되는 제품입니다.',
      severity: 'MEDIUM',
    },
  ],
  attention_products: [
    {
      check_id: 35,
      product_id: 102,
      product_name: '밀크 프로틴 보습 물티슈',
      overall_status: 'FAIL',
      status_label: '사용 보류',
      summary: '사용 보류 1명, 주의 필요 1명',
      children: [
        { child_id: 1, child_name: '강민준', status: 'FAIL', status_label: '사용 보류' },
        { child_id: 2, child_name: '김서아', status: 'WARN', status_label: '주의 필요' },
      ],
    },
  ],
}
